CREATE DATABASE IF NOT EXISTS BD_BICLIOTECA_2ANO;
USE REDE_BIBLIOTECA_2ANO;

CREATE TABLE IF NOT EXISTS AUTOR (
	CPF VARCHAR (20) PRIMARY KEY,
    NOME VARCHAR (200) NOT NULL,
    GENERO VARCHAR (30) NOT NULL,
    CONTATO VARCHAR (20) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR (255) ,
    GENERO VARCHAR (255)
);

CREATE TABLE IF NOT EXISTS LEITOR (
	CPF VARCHAR (20) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    TELEFONE VARCHAR (20)NOT NULL,
    EMAIL VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ACESSAR (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_LIVRO INTEGER,
    FK_CPF_LEITOR VARCHAR (20),
    FOREIGN KEY ( FK_ID_LIVRO) REFERENCES LIVRO (ID),
    FOREIGN KEY ( FK_CPF_LEITOR) REFERENCES LEITOR (CPF)
);