CREATE DATABASE IF NOT EXISTS BD_ESCOLA_2ANO;
USE BD_ESCOLA_2ANO;

CREATE TABLE IF NOT EXISTS PROFESSOR (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    TITULACAO INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUNO(
	RM INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CURSO (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR (255) NOT NULL,
    CARGA_HORA VARCHAR (10) NOT NULL,
    FK_PROFESSOR_ID INTEGER,
    FOREIGN KEY (FK_PROFESSOR_ID) REFERENCES PROFESSOR (ID)
);

CREATE TABLE IF NOT EXISTS CURSO_ALUNO (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CURSO_ID INTEGER,
    FK_ALUNO_RM INTEGER,
    FOREIGN KEY (FK_CURSO_ID) REFERENCES CURSO (ID),
    FOREIGN KEY (FK_ALUNO_RM) REFERENCES ALUNO (RM)
);