CREATE DATABASE IF NOT EXISTS BD_GERENCIAMENTO_PROJETOS_2ANO;
USE BD_GERENCIAMENTO_PROJETOS_2ANO;

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRAZO DATE NOT NULL,
    DEMANDA VARCHAR (100) NOT NULL,
    VALOR DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO (
	CPF VARCHAR (20) PRIMARY KEY,
    TELEFONE VARCHAR (20) NOT NULL,
    DEVER VARCHAR (255)
);

CREATE TABLE IF NOT EXISTS TAREFA (
	 ID INTEGER AUTO_INCREMENT PRIMARY KEY,
     PRAZO DATE NOT NULL,
     DEMANDA VARCHAR (255) NOT NULL,
     VALOR DOUBLE NOT NULL,
     FK_PROJETO_ID INTEGER,
     FK_FUNCIONARIO_CPF VARCHAR (20),
     FOREIGN KEY (FK_PROJETO_ID) REFERENCES PROJETO (ID),
     FOREIGN KEY (FK_FUNCIONARIO_CPF) REFERENCES FUNCIONARIO (CPF)
);

CREATE TABLE IF NOT EXISTS TAREFA_FUNCIONARIO (
	FK_TAREFA_ID INTEGER,
    FK_FUNCIONARIO_CPF VARCHAR (20),
    FOREIGN KEY (FK_TAREFA_ID) REFERENCES TAREFA (ID),
    FOREIGN KEY (FK_FUNCIONARIO_CPF) REFERENCES FUNCIONARIO (CPF)
);