CREATE DATABASE IF NOT EXISTS BD_RESERVA_HOTEL_2ANO;
USE BD_RESERVA_HOTEL_2ANO;

CREATE TABLE IF NOT EXISTS HOTEL (
	 CNPJ VARCHAR (20) PRIMARY KEY,
     EMAIL VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS HOSPEDE (
	CPF VARCHAR (20) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS QUARTO (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	NUMERO INTEGER NOT NULL,
	FK_HOTEL_CNPJ VARCHAR (20),
    FOREIGN KEY (FK_HOTEL_CNPJ) REFERENCES HOTEL (CNPJ)
);

CREATE TABLE IF NOT EXISTS QUARTO_HOSPEDE (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_QUARTO_ID INTEGER,
    FK_HOSPEDE_CPF VARCHAR (20),
    FOREIGN KEY (FK_QUARTO_ID) REFERENCES QUARTO (ID),
    FOREIGN KEY (FK_HOSPEDE_CPF) REFERENCES HOSPEDE (CPF)
);


DROP TABLE QUARTO;