CREATE DATABASE IF NOT EXISTS BD_GESTAO_ESTOQUE_2ANO;
USE BD_GESTAO_ESTOQUE_2ANO;

CREATE TABLE IF NOT EXISTS CATEGORIA (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR (255) NOT NULL,
    NOME VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VALIDADE DATE NOT NULL,
    NOME VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDOR (
	CNPJ VARCHAR (20) PRIMARY KEY,
    EMAIL VARCHAR (255) NOT NULL,
    NOME VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO_FORNECEDOR (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_FORNECEDOR_CNPJ VARCHAR (20),
    FK_PRODUTO_ID INTEGER,
    FOREIGN KEY (FK_FORNECEDOR_CNPJ) REFERENCES FORNECEDOR (CNPJ),
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO (ID)
);

DROP TABLE PRODUTO_FORNECEDOR