CREATE DATABASE IF NOT EXISTS BD_APLICATIVO_MUSICA_2ANO;
USE BD_APLICATIVO_MUSICA_2ANO;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR (15) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    TELEFONE VARCHAR (20) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    RITMO VARCHAR (50),
    PUBLICO_ALVO VARCHAR (50)
);

CREATE TABLE IF NOT EXISTS ALBUM (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    MUSICA VARCHAR (10) NOT NULL,
    NOME VARCHAR (255) NOT NULL,
    CAPA BLOB NOT NULL,
    FK_ARTISTA_CPF VARCHAR (15),
    FOREIGN KEY (FK_ARTISTA_CPF) REFERENCES ARTISTA (CPF)
);

CREATE TABLE IF NOT EXISTS FAIXA (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    DURACAO VARCHAR (10) NOT NULL,
    FK_GENERO_ID INTEGER,
    FK_ALBUM_ID INTEGER,
    FOREIGN KEY (FK_GENERO_ID) REFERENCES GENERO (ID),
    FOREIGN KEY (FK_ALBUM_ID) REFERENCES ALBUM (ID)
);

DROP TABLE ALBUM;