CREATE DATABASE IF NOT EXISTS BD_PASSAGENS_2ANO;
USE BD_PASSAGENS_2ANO;

CREATE TABLE IF NOT EXISTS VOO (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LOCAL VARCHAR (255),
    DATA DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR (20) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    TELEFONE VARCHAR (20) NOT NULL,
    BAGAGEM VARCHAR (5) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO (
	NUMERO VARCHAR (4) PRIMARY KEY,
    CONFORTO VARCHAR (20),
    LOCAL VARCHAR (20) NOT NULL,
    FK_VOO_ID INTEGER,
    FK_PASSAGEIRO_CPF VARCHAR (20),
    FOREIGN KEY (FK_VOO_ID) REFERENCES VOO (ID),
    FOREIGN KEY (FK_PASSAGEIRO_CPF) REFERENCES PASSAGEIRO (CPF)
);

DROP TABLE ASSENTO;