CREATE DATABASE IF NOT EXISTS BD_VIDEO_2ANO;
USE BD_VIDEO_2ANO;

CREATE TABLE IF NOT EXISTS CATEGORIA (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR (255),
    IDADE INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS VIDEO (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (30) NOT NULL,
    TEMPO VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS VIZUALIZACAO (
	 ID INTEGER AUTO_INCREMENT PRIMARY KEY,
     INTERACAO VARCHAR (255),
     FK_VIDEO_ID INTEGER,
     FOREIGN KEY (FK_VIDEO_ID) REFERENCES VIDEO (ID)
);