CREATE DATABASE IF NOT EXISTS BD_ALUGUEL_PRODUTOS_2ANO;
USE BD_ALUGUEL_PRODUTOS_2ANO;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLIENTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR (255) NOT NULL,
    CPF VARCHAR (15) NOT NULL,
    NOME VARCHAR (255) NOT NULL,
    TELEFONE VARCHAR (15) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	PRODUTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    DESCRICAO VARCHAR (500) NOT NULL,
    PRECO DECIMAL NOT NULL,
    QTD_DISPONIVEL INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL (
	ALUGUEL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_ALUGUEL DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,
    VALOR_TOTAL DECIMAL NOT NULL,
    FK_CLIENTE_ID INTEGER NOT NULL,
    FK_PRODUTO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CLIENTE_ID) REFERENCES CLIENTE (CLIENTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO (PRODUTO_ID) ON DELETE CASCADE
);

-- DML -LINGUAGEM DE MANIPULAÇÃO
-- INSERT - INSERIR

INSERT INTO CLIENTE (EMAIL, CPF, NOME, TELEFONE)
VALUES ("email@gmail.com", "531.427.148.56", "Emily", "19989847148");

INSERT INTO CLIENTE (EMAIL, CPF, NOME, TELEFONE)
VALUES ("emilymaiara@gmail.com", "531.427.148.63", "Emily Maiara", "19995083585");

INSERT INTO CLIENTE (NOME, CPF, EMAIL, TELEFONE)
VALUES ("Izabel", "09593434828", "izabel@gmail.com", "19989847147");

-- select - selecionar
SELECT * FROM CLIENTE;

-- INSERIR PRODUTOS

INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES ("MacBook", "Notebook Aplle", 4789.90, 5);

INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES ("Iphone 17", "Celular", 17000, 5);

INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES ("TV", "Televisão", 2499, 158);

INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES ("Ipad", "Tablet Apple", 2448, 20);

INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES ("Air Pods", "Fone Apple", 147.17, 100);

INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES ("Geladeira", "Geladeira", 9.999, 1400);

INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES ("Aplle Whatc", "Relogio Apple", 1.544, 89);

INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES ("Labubu", "Pelucia", 59.9, 999);

INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES ("mesa", "movel", 100.99, 1485);

INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES ("PS5", "Jogo", 5.499, 178);

SELECT * FROM PRODUTO;

-- inserir aluguel	

SELECT * FROM CLIENTE;
SELECT * FROM PRODUTO;

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-09-30", 7890, 3, 2);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-10-06", 20, 1, 7);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-10-07", 200, 2, 7);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-11-20", 499, 3, 8);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-11-09", 177, 2, 4);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-12-02", 469, 1, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-12-01", 326, 1, 10);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-09-25", 77, 2, 7);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-11-06", 359, 3, 3);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-12-07", 32, 3, 9);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-12-25", 47, 2, 8);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-12-29", 220, 1, 2);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-12-04", 9635, 1, 5);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-11-05", 436, 2, 4);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-11-30", 469, 3, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-09-27", 896, 3, 6);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-11-16", 44, 2, 2);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-11-05", 36, 1, 4);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-11-05", 128, 2, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-11-05", 6, 2, 7);

SELECT * FROM ALUGUEL;
SELECT * FROM PRODUTO;
SELECT * FROM CLIENTE;

-- ATUALIZAR UM REGISTRO - UPDATE

UPDATE PRODUTO 
SET PRECO = 3500
WHERE PRODUTO_ID = 1;

UPDATE PRODUTO 
SET PRECO = 214
WHERE PRODUTO_ID = 2;

UPDATE PRODUTO 
SET PRECO = 999
WHERE PRODUTO_ID = 3;

UPDATE PRODUTO 
SET QTD_DISPONIVEL = 1
WHERE PRODUTO_ID = 1;

UPDATE PRODUTO 
SET QTD_DISPONIVEL = 15
WHERE PRODUTO_ID = 2;

UPDATE PRODUTO 
SET QTD_DISPONIVEL = 999
WHERE PRODUTO_ID = 3;

UPDATE PRODUTO 
SET QTD_DISPONIVEL = 9999
WHERE PRODUTO_ID = 4;

UPDATE PRODUTO 
SET QTD_DISPONIVEL = 99999
WHERE PRODUTO_ID = 5;

UPDATE CLIENTE 
SET EMAIL = "email@outlook"
WHERE CLIENTE_ID = 1;

UPDATE CLIENTE 
SET EMAIL = "emilynda@outlook"
WHERE CLIENTE_ID = 2;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-12-25"
WHERE ALUGUEL_ID = 1;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-12-24"
WHERE ALUGUEL_ID = 2;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-12-23"
WHERE ALUGUEL_ID = 3;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-12-05"
WHERE ALUGUEL_ID = 4;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-12-12"
WHERE ALUGUEL_ID = 5;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-12-30"
WHERE ALUGUEL_ID = 6;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-12-01"
WHERE ALUGUEL_ID = 7;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-12-09"
WHERE ALUGUEL_ID = 8;

-- APAGAR UM REGISTRO (DELETE)

DELETE FROM CLIENTE WHERE CLIENTE_ID = 1;
DELETE FROM ALUGUEL WHERE ALUGUEL_ID = 1;
DELETE FROM PRODUTO WHERE PRODUTO_ID = 4;

-- FILTRAR O SELECT

SELECT *
FROM CLIENTE
WHERE CLIENTE_ID = 2;


-- MOSTRAR SO UMA COLUNA
SELECT NOME, PRECO
FROM PRODUTO 
WHERE PRODUTO_ID = 3;